import Foundation
import Combine
// MARK: - Gemini API Service
// Handles communication with Google Gemini AI API for educational content generation

// MARK: - Data Models

/// Represents educational content generated by Gemini AI
struct EducationalContent: Codable, Identifiable {
    let id: String
    let title: String
    let detectedObjectName: String
    let category: String
    let shortSummary: String
    let educationalFacts: [String]
    let difficultyLevel: String // "Beginner", "Intermediate", "Advanced"
    let keyLearningPoints: [String]
    let quizQuestions: [EVDiscoveryQuizQuestion]
    let arOverlayCaption: String
    let extractedText: String
    let generatedAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id, title, detectedObjectName, category, shortSummary, educationalFacts
        case difficultyLevel, keyLearningPoints, quizQuestions, arOverlayCaption
        case extractedText, generatedAt
    }
}

/// Represents a multiple-choice quiz question
struct EVDiscoveryQuizQuestion: Codable, Identifiable {
    let id: String
    let question: String
    let options: [String]
    let correctAnswerIndex: Int
    let explanation: String
    
    enum CodingKeys: String, CodingKey {
        case id, question, options, correctAnswerIndex, explanation
    }
}

/// Request payload for Gemini API
struct GeminiRequest: Codable {
    let contents: [ContentBlock]
    
    struct ContentBlock: Codable {
        let parts: [Part]
    }
    
    struct Part: Codable {
        let text: String
    }
}

/// Response from Gemini API
struct GeminiResponse: Codable {
    let candidates: [Candidate]
    
    struct Candidate: Codable {
        let content: ContentBlock
        
        struct ContentBlock: Codable {
            let parts: [Part]
            
            struct Part: Codable {
                let text: String
            }
        }
    }
}

// MARK: - Gemini API Service

@MainActor
class GeminiAPIService: ObservableObject {
    static let shared = GeminiAPIService()
    
    private let apiKey: String
    private let apiVersions = ["v1", "v1beta"]
    private let modelCandidates = [
        "gemini-2.5-flash",
        "gemini-2.0-flash",
        "gemini-2.0-flash-lite",
        "gemini-1.5-flash",
        "gemini-1.5-flash-latest",
        "gemini-1.5-pro"
    ]
    private var discoveredModelCandidates: [String] = []
    
    private init() {
        // Get API key from environment or use placeholder
        // In production, fetch from Firebase Remote Config or secure storage
        self.apiKey = ProcessInfo.processInfo.environment["GEMINI_API_KEY"] ?? ""
    }
    
    /// Set the API key (called during app initialization)
    func setAPIKey(_ key: String) {
        let trimmedKey = key.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedKey.isEmpty else {
            print("⚠️ Warning: Empty Gemini API key provided")
            return
        }
        // Store in UserDefaults or Keychain for secure access
        UserDefaults.standard.set(trimmedKey, forKey: "com.edventure.gemini_api_key")
    }
    
    /// Get stored API key
    private func getAPIKey() -> String {
        let key = UserDefaults.standard.string(forKey: "com.edventure.gemini_api_key") ?? apiKey
        return key.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    
    /// Generate educational content from extracted text
    /// - Parameter extractedText: OCR text extracted from the image
    /// - Returns: Structured educational content
    func generateEducationalContent(from extractedText: String) async throws -> EducationalContent {
        let key = getAPIKey()
        guard !key.isEmpty else {
            throw GeminiError.missingAPIKey
        }
        
        let prompt = buildEducationalPrompt(from: extractedText)
        let request = buildRequest(with: prompt)

        if discoveredModelCandidates.isEmpty {
            discoveredModelCandidates = await fetchAvailableGeminiModels(key: key)
        }

        let modelsToTry = discoveredModelCandidates.isEmpty ? modelCandidates : discoveredModelCandidates

        var lastStatusCode: Int?
        var sawRateLimit = false

        for version in apiVersions {
            for model in modelsToTry {
                do {
                    let responseText = try await requestCompletionTextWithRetry(version: version, model: model, key: key, request: request)
                    let content = try parseEducationalContent(responseText, extractedText: extractedText)
                    return content
                } catch GeminiError.apiError(let statusCode) {
                    lastStatusCode = statusCode
                    if statusCode == 429 {
                        sawRateLimit = true
                    }
                    // Keep trying on model/version misses and transient server/rate-limit failures.
                    if statusCode == 404 || isRetryableStatus(statusCode) { continue }
                    throw GeminiError.apiError(statusCode: statusCode)
                }
            }
        }

        if sawRateLimit {
            throw GeminiError.apiError(statusCode: 429)
        }
        throw GeminiError.apiError(statusCode: lastStatusCode ?? 404)
    }
    
    // MARK: - Private Helpers
    
    private func buildEducationalPrompt(from text: String) -> String {
        return """
        Analyze the following text extracted from a real-world educational object (book, poster, label, document, etc.) and generate comprehensive educational content.

        EXTRACTED TEXT:
        \(text)

        RESPOND WITH A JSON OBJECT containing EXACTLY this structure (no markdown, no explanations, just valid JSON):
        {
            "title": "Name/title of the object",
            "detectedObjectName": "Type of object (e.g., 'Book Cover', 'Educational Poster')",
            "category": "astronomy|computer_science|philosophy|biology|mathematics",
            "shortSummary": "2-3 sentence summary of the content",
            "educationalFacts": ["fact1", "fact2", "fact3", "fact4"],
            "difficultyLevel": "Beginner|Intermediate|Advanced",
            "keyLearningPoints": ["point1", "point2", "point3"],
            "quizQuestions": [
                {
                    "question": "First multiple choice question?",
                    "options": ["Option A", "Option B", "Option C", "Option D"],
                    "correctAnswerIndex": 0,
                    "explanation": "Why this is correct"
                },
                {
                    "question": "Second multiple choice question?",
                    "options": ["Option A", "Option B", "Option C", "Option D"],
                    "correctAnswerIndex": 1,
                    "explanation": "Why this is correct"
                },
                {
                    "question": "Third multiple choice question?",
                    "options": ["Option A", "Option B", "Option C", "Option D"],
                    "correctAnswerIndex": 2,
                    "explanation": "Why this is correct"
                }
            ],
            "arOverlayCaption": "Brief educational caption for AR display (max 15 words)"
        }

        IMPORTANT:
        - Return ONLY valid JSON, no other text
        - Ensure all quiz questions have exactly 4 options
        - Generate 5 questions when possible (4-6 acceptable)
        - Keep facts and learning points concise
        - Make content educationally valuable
        """
    }
    
    private func buildRequest(with prompt: String) -> GeminiRequest {
        return GeminiRequest(
            contents: [
                GeminiRequest.ContentBlock(
                    parts: [
                        GeminiRequest.Part(text: prompt)
                    ]
                )
            ]
        )
    }

    private func requestCompletionText(version: String, model: String, key: String, request: GeminiRequest) async throws -> String {
        var components = URLComponents()
        components.scheme = "https"
        components.host = "generativelanguage.googleapis.com"
        components.path = "/\(version)/models/\(model):generateContent"
        components.queryItems = [URLQueryItem(name: "key", value: key)]

        guard let url = components.url else {
            throw GeminiError.invalidResponse
        }

        var urlRequest = URLRequest(url: url)
        urlRequest.httpMethod = "POST"
        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
        urlRequest.httpBody = try JSONEncoder().encode(request)

        let (data, response) = try await URLSession.shared.data(for: urlRequest)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw GeminiError.invalidResponse
        }

        guard (200...299).contains(httpResponse.statusCode) else {
            print("❌ Gemini API Error (\(version)/\(model)): Status \(httpResponse.statusCode)")
            if let errorText = String(data: data, encoding: .utf8) {
                print("Response: \(errorText)")
            }
            throw GeminiError.apiError(statusCode: httpResponse.statusCode)
        }

        let geminiResponse = try JSONDecoder().decode(GeminiResponse.self, from: data)
        guard let responseText = geminiResponse.candidates.first?.content.parts.first?.text else {
            throw GeminiError.invalidResponse
        }
        return responseText
    }

    private func requestCompletionTextWithRetry(version: String, model: String, key: String, request: GeminiRequest) async throws -> String {
        let maxAttempts = 3
        var lastError: Error?

        for attempt in 1...maxAttempts {
            do {
                return try await requestCompletionText(version: version, model: model, key: key, request: request)
            } catch GeminiError.apiError(let statusCode) {
                lastError = GeminiError.apiError(statusCode: statusCode)
                guard isRetryableStatus(statusCode), attempt < maxAttempts else {
                    throw GeminiError.apiError(statusCode: statusCode)
                }
                let delay = UInt64(attempt * 500_000_000) // 0.5s, 1.0s
                try? await Task.sleep(nanoseconds: delay)
            } catch {
                lastError = error
                if attempt < maxAttempts {
                    let delay = UInt64(attempt * 500_000_000)
                    try? await Task.sleep(nanoseconds: delay)
                    continue
                }
                throw GeminiError.networkError(error)
            }
        }

        if let geminiError = lastError as? GeminiError {
            throw geminiError
        }
        throw GeminiError.invalidResponse
    }

    private func isRetryableStatus(_ statusCode: Int) -> Bool {
        statusCode == 429 || (500...599).contains(statusCode)
    }

    private func fetchAvailableGeminiModels(key: String) async -> [String] {
        var discovered: [String] = []

        for version in apiVersions {
            do {
                var components = URLComponents()
                components.scheme = "https"
                components.host = "generativelanguage.googleapis.com"
                components.path = "/\(version)/models"
                components.queryItems = [URLQueryItem(name: "key", value: key)]

                guard let url = components.url else { continue }

                let (data, response) = try await URLSession.shared.data(from: url)
                guard let http = response as? HTTPURLResponse,
                      (200...299).contains(http.statusCode) else {
                    continue
                }

                let payload = try JSONDecoder().decode(GeminiModelsListResponse.self, from: data)
                let models = payload.models
                    .filter { $0.supportedGenerationMethods.contains("generateContent") }
                    .map { $0.name.replacingOccurrences(of: "models/", with: "") }
                    .filter { $0.lowercased().contains("gemini") }

                if !models.isEmpty {
                    discovered = models
                    break
                }
            } catch {
                continue
            }
        }

        return discovered
    }
    
    private func parseEducationalContent(_ jsonText: String, extractedText: String) throws -> EducationalContent {
        // Remove markdown code blocks if present
        var cleanJson = jsonText
        if cleanJson.contains("```") {
            let components = cleanJson.components(separatedBy: "```")
            if components.count >= 2 {
                cleanJson = components[1]
            }
        }
        cleanJson = cleanJson.replacingOccurrences(of: "json", with: "").trimmingCharacters(in: .whitespaces)
        
        guard let jsonData = cleanJson.data(using: .utf8) else {
            throw GeminiError.invalidJSON
        }
        
        let decoder = JSONDecoder()
        let contentDict = try decoder.decode(GeminiContentDict.self, from: jsonData)
        
        let id = UUID().uuidString
        let limitedQuestions = Array(contentDict.quizQuestions.prefix(6))
        let quizQuestions = limitedQuestions.enumerated().map { index, q in
            EVDiscoveryQuizQuestion(
                id: "\(id)_q\(index)",
                question: q.question,
                options: q.options,
                correctAnswerIndex: q.correctAnswerIndex,
                explanation: q.explanation
            )
        }
        
        let content = EducationalContent(
            id: id,
            title: contentDict.title,
            detectedObjectName: contentDict.detectedObjectName,
            category: resolveCategory(contentDict.category),
            shortSummary: contentDict.shortSummary,
            educationalFacts: contentDict.educationalFacts,
            difficultyLevel: contentDict.difficultyLevel,
            keyLearningPoints: contentDict.keyLearningPoints,
            quizQuestions: quizQuestions,
            arOverlayCaption: contentDict.arOverlayCaption,
            extractedText: extractedText,
            generatedAt: Date()
        )
        
        return content
    }

    private func resolveCategory(_ raw: String?) -> String {
        let normalized = (raw ?? "").lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        switch normalized {
        case "astronomy", "computer_science", "philosophy", "biology", "mathematics":
            return normalized
        default:
            return "computer_science"
        }
    }
}

// MARK: - Helper Structures for Parsing

struct GeminiContentDict: Codable {
    let title: String
    let detectedObjectName: String
    let category: String?
    let shortSummary: String
    let educationalFacts: [String]
    let difficultyLevel: String
    let keyLearningPoints: [String]
    let quizQuestions: [QuizQuestionDict]
    let arOverlayCaption: String
    
    enum CodingKeys: String, CodingKey {
        case title, detectedObjectName, category, shortSummary, educationalFacts
        case difficultyLevel, keyLearningPoints, quizQuestions, arOverlayCaption
    }
}

struct QuizQuestionDict: Codable {
    let question: String
    let options: [String]
    let correctAnswerIndex: Int
    let explanation: String
}

private struct GeminiModelsListResponse: Codable {
    let models: [GeminiModel]

    struct GeminiModel: Codable {
        let name: String
        let supportedGenerationMethods: [String]
    }
}

// MARK: - Error Handling

enum GeminiError: LocalizedError {
    case missingAPIKey
    case invalidResponse
    case invalidJSON
    case apiError(statusCode: Int)
    case networkError(Error)
    
    var errorDescription: String? {
        switch self {
        case .missingAPIKey:
            return "Gemini API key is not configured"
        case .invalidResponse:
            return "Invalid response from Gemini API"
        case .invalidJSON:
            return "Failed to parse AI response"
        case .apiError(let statusCode):
            return "Gemini API error: Status \(statusCode)"
        case .networkError(let error):
            return "Network error: \(error.localizedDescription)"
        }
    }
}
